#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: .keystore
#    key-store-password: qovh!1234
#    key-store-type: PKCS12

spring:
  h2:
    console:
      enabled: true
      path: /test_db
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:./h2/test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
        
logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    
file:
  path: /Users/heyho.se/storages/vhere # C:/storages/vhere